config/routes.rb
Rails.application.routes.draw do

  namespace :public do
    get 'relationships/followings'
    get 'relationships/followers'
  end

  devise_for :users, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  scope module: :public do
    root :to => "homes#top"
    get "homes/about"
    get "posts/select_prefecture"
    get "posts/new/:id" => "posts#new", as: "post_new"
    resources :posts, only: [:index, :show, :create, :update] do
      resources :comments, only: [:create, :destroy]
      resources :bookmarks, only: [:create, :destroy]
    end
    resources :image_tags, only: [:destroy]
    resources :area_ratings, only: [:create]
    resources :records, only: [:create, :update, :destroy]
    resources :areas, only: [:show, :update]
    resources :prefectures, only: [:show]
    resources :regions, only: [:index]
    resources :information, only: [:index, :show]
    resources :users, only: [:show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
  end

  namespace :admin do
    root :to =>"homes#top"
    resources :posts, only: [:index, :show, :update, :destroy] do
      resources :comments, only: [:destroy]
    end
    resources :users, only: [:index, :show, :update]
    resources :areas, only: [:index, :create, :destroy, :update]
    resources :species, only: [:index, :create, :destroy]
    resources :fishing_methods, only: [:index, :create, :destroy]
    resources :information, only: [:index, :create, :destroy, :update, :new]
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord

  validates :prefecture_id, :name, :longitude, :latitude, presence: true

  belongs_to :prefecture
  has_many   :posts
  has_many   :area_ratings
  has_many_attached :image

  def get_image
    if image.attached?
      image[0]
    else
      "noimage.png"
    end
  end

end

app/models/area_rating.rb
class AreaRating < ApplicationRecord

  validates :user_id, :area_id, :comment, :score, presence: true

  belongs_to :area
  belongs_to :user
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord

  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: { scope: :post_id }

end

app/models/comment.rb
class Comment < ApplicationRecord

  validates :post_id, :user_id, :comment, presence: true

  belongs_to :user
  belongs_to :post

end

app/models/fishing_method.rb
class FishingMethod < ApplicationRecord

  validates :name, presence: true

  has_many :posts
end

app/models/image_tag.rb
class ImageTag < ApplicationRecord
	belongs_to :post
end

app/models/information.rb
class Information < ApplicationRecord

  validates :title, :body, presence: true

  has_many_attached :image

  def get_image
    if image.attached?
      image[0]
    else
      "noimage.png"
    end
  end

end

app/models/post.rb
class Post < ApplicationRecord

  validates :species_id, :user_id, :area_id, :fishing_method_id, :date, :time_zone_id, :catch_number, :comment, :title, presence: true

  belongs_to :user
  belongs_to :area
  belongs_to :species
  belongs_to :fishing_method
  belongs_to :time_zone
  has_many :image_tags, dependent: :destroy
  has_many   :post_tags, dependent: :destroy
  has_many   :prefectures, through: :post_tags
  has_many   :comments, dependent: :destroy
  has_many   :bookmarks, dependent: :destroy
  has_many_attached :image

  def bookmarked_by?(user)
    bookmarks.where(user_id: user).exists?
  end

  def get_post_image
    if image.attached?
      image[0]
    else
      "noimage.png"
    end
  end

  def self.search(search)
    if search
      where(['title LIKE ?', "%#{search}%"]) #検索とタイトルの部分一致を表示。
    else
      all #全て表示させる
    end
  end


end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :prefecture
end

app/models/prefecture.rb
class Prefecture < ApplicationRecord
  has_many :area
  has_many :users
  has_many :post_tags, dependent: :destroy
  has_many :posts, through: :post_tags
  belongs_to :region
  has_many_attached :image

  def get_post_image
    if image.attached?
      image[0]
    else
      "noimage.png"
    end
  end

  def get_prefecture_image(prefecture)
    "prefectures/#{prefecture.name}.png"
  end

end

app/models/record.rb
class Record < ApplicationRecord

  validates :user_id, :species_id, :size, :catch_number, presence: true

  belongs_to :user
  belongs_to :species
end

app/models/region.rb
class Region < ApplicationRecord

  has_many :prefecture

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/species.rb
class Species < ApplicationRecord

  validates :species, presence: true

  has_many :posts
  has_many :records
end

app/models/time_zone.rb
class TimeZone < ApplicationRecord
  has_many :posts
end

app/models/user.rb
class User < ApplicationRecord
  has_many   :posts, dependent: :destroy
  has_many   :bookmarks, dependent: :destroy
  has_many   :comments, dependent: :destroy
  has_many   :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many   :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many   :followings, through: :relationships, source: :followed, dependent: :destroy
  has_many   :followers, through: :reverse_of_relationships, source: :follower, dependent: :destroy
  has_many   :area_ratings, dependent: :destroy
  has_many   :records, dependent: :destroy
  belongs_to :prefecture
  has_one_attached :image
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def get_image
    if image.attached?
      image
    else
      "noimage.png"
    end
  end

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController

  before_action :authenticate_admin!

  def show
    @post = Post.find(params[:id]) #データを1件取得
  end

  def index
    @posts = Post.all.page(params[:page]).per(15) #全ての投稿データを取得
  end

  def update
    post = Post.find(params[:id]) #データを1件取得
    post.update(post_params) #データを保存
    redirect_to request.referer #元の画面へリダイレクト
  end

  def destroy
    post = Post.find(params[:id]) #データを1件取得
    post.destroy #データを削除
    redirect_to admin_root_path #管理者用初期画面へリダイレクト
  end


  private

  def post_params #受信するデータの選択
    params.require(:post).permit(:species_id, :user_id, :area_id, :fishing_method_id, :prefecture_id, :date, :time_zone_id, :catch_number, :catch_other, :comment, :title, :image, :status)
  end

end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/posts/index.html.erb
<!-- ヘッダー -->
<header class="bg-dark py-4">
  <div class="container px-4 px-lg-5">
    <div class="text-center text-white">
      <h2 class="fw-bolder">投稿一覧</h2>
    </div>
  </div>
</header>
<!-- 投稿の一覧を表示 -->
<section class="bg-light">
  <div class="container-fluid px-0">
    <div class="row">
      <%= render "admin/homes/sidebar" %>
      <div class="col-10 px-4">
        <table class="table my-3">
          <tr>
            <th>投稿日</th>
            <th>ユーザー名</th>
            <th>投稿タイトル</th>
            <th>コメント数</th>
            <th></th>
          </tr>
          <% @posts.each do |post| %>
            <tr>
              <td><%= post.created_at.strftime('%Y/%m/%d') %></td>
              <td><%= post.user.name %></td>
              <td><%= link_to "#{post.title}", admin_post_path(post), class: "text-dark " %></td>
              <td><%= post.comments.count %>件</td>
              <td><%= link_to "投稿を削除", admin_post_path(post), class: "btn btn-danger btn-sm", method: :delete, "data-confirm" => "本当に削除しますか？" %></td>
            </tr>
          <% end %>
        </table>
      </div>
    </div>
    <div class="row">
      <!-- ページネーションのページ選択 -->
      <div class="text-center mx-auto mb-2"><%= paginate @posts %></div>
    </div>
  </div>
</section>

app/views/admin/posts/show.html.erb
<!-- ヘッダー -->
<header class="bg-dark py-4">
  <div class="container px-4 px-lg-5">
    <div class="text-center text-white">
      <h2 class="fw-bolder">投稿詳細</h2>
    </div>
  </div>
</header>
<!-- 投稿画像についてを表示する部分 -->
<section class="bg-light">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <!-- 投稿された画像を表示する -->
      <%= image_tag @post.get_post_image, height: "400", class: "mx-auto d-block py-4" %>
      <!-- Natural Language APIで作成したタグを表示 -->
      <div class="tag-box text-center mb-3">
        <div class="text-dark mt-2 text-center">AIによるタグ付け</div>
        <!-- 投稿の画像に付いているタグを全て表示 -->
        <% @post.image_tags.each do |image_tag| %>
          <span><a class="btn btn-outline-dark btn-sm mt-2"><%= image_tag.name %></a></span>
        <% end %>
      </div>
    </div>
  </div>
</section>
<!-- 投稿内容について表示する部分 -->
<section class="bg-light">
  <div class="row">
    <table class="col-lg-8 offset-lg-2 table">
      <tr>
        <th class="text-center" sytle="width: 200px">投稿タイトル</th>
        <td>
          <%= @post.title %>
          <!-- 投稿をブックマークするボタンを表示 -->
          <!-- ログインしていない場合ボタンは表示しない -->
          <% if user_signed_in? %>
            <!-- 既にブックマークしている場合はブックマークを外すボタンを表示 -->
            <% if @post.bookmarked_by?(current_user) %>
              <%= link_to "ブックマークを外す", post_bookmark_path(@post), class: "btn btn-outline-danger btn-sm text-right", method: :delete %>
            <!-- まだブックマークしていない場合はブックマークするボタンを表示 -->
            <% else %>
              <%= link_to "投稿をブックマーク", post_bookmarks_path(@post), class: "btn btn-outline-primary btn-sm text-right", method: :post %>
            <% end %>
          <% end %>
        </td>
      </tr>
      <tr>
        <th class="text-center" style="width: 200px">投稿ユーザー</th>
        <td>
          <!-- 投稿ユーザー名 -->
          <div><%= @post.user.name %>さん
            <!-- ログインしている場合フォローボタンを表示 -->
            <% if user_signed_in? %>
              <!-- 投稿ユーザーとログインユーザーが一致しない場合フォローボタンを表示 -->
              <% if current_user.id != @post.user_id %>
                <!-- 未フォローの場合はフォローする、既にフォローしている場合はフォローを外す -->
                <% if current_user.following?(@post.user) %>
                  <%= link_to "フォロー外す", user_relationships_path(@post.user.id), class: "btn btn-outline-danger btn-sm", method: :delete %>
                <% else %>
                  <%= link_to "フォローする", user_relationships_path(@post.user.id), class: "btn btn-outline-primary btn-sm", method: :post %>
                <% end %>
              <% end %>
            <% end %>
          </div>
        </td>
      </tr>
      <!-- 釣行日および時間帯 -->
      <tr>
        <th class="text-center">釣行日・時間帯</th>
        <td><%= @post.date %> <%= @post.time_zone.time_zone %></td>
      </tr>
      <!-- 釣り場 -->
      <tr>
        <th class="text-center">釣り場</th>
        <td><%= @post.area.name %></td>
      </tr>
      <!-- 釣果 -->
      <tr>
        <th class="text-center">メインの釣果</th>
        <td><%= @post.species.name %> <%= @post.catch_number %>匹</td>
      </tr>
      <!-- 釣法 -->
      <tr>
        <th class="text-center">釣法</th>
        <td><%= @post.fishing_method.name %></td>
      </tr>
      <!-- 投稿コメント -->
      <tr>
        <th class="text-center">投稿者のコメント</th>
        <td><%= @post.comment %></td>
      </tr>
    </table>
    <!-- 投稿に対するコメント -->
    <div class="col-12 col-lg-6 offset-lg-3 mb-3">
      <!-- 投稿に対するコメントの一覧を表示 -->
      <div>
        <!-- 投稿に対して付いているコメントの件数を表示 -->
        <div class="text-center my-2 border-bottom">コメント件数：<%= @post.comments.count %></div>
        <!-- コメントの一覧を表示 -->
        <% @post.comments.each do |comment| %>
          <!-- コメントをした人の名前 -->
          <div class="px-4"><%= comment.user.name %>さん</div>
          <!-- コメントの内容 -->
          <div class="px-4 mx-3"><%= comment.comment %></div>
          <!-- コメントの投稿日 -->
          <div class="text-right px-4"><%= comment.created_at.strftime('%Y/%m/%d') %></div>
          <div class="text-right px-4 border-bottom"><%= link_to "コメントを削除", admin_post_comment_path(@post, comment), class: "btn btn-outline-danger mb-2", method: :delete, "data-confirm" => "本当に削除しますか？" %></div>
        <% end %>
      </div>
      <!-- 投稿に対するコメントを投稿するフォームを表示 -->
      <div>
        <!-- ログインしていない場合は入力フォームを表示しない -->
        <% if user_signed_in? %>
          <%= form_with model: [@post, @comment] do |f| %>
            <!-- コメント入力フォーム -->
            <div class="text-center px-3"><%= f.text_area :comment, rows: "5", placeholder: "コメントを入力", class: "mt-3 w-100" %></div>
            <!-- 投稿ボタン -->
            <div class="text-center px-3"><%= f.submit "送信", class: "btn btn-success w-100" %></div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</section>