config/routes.rb
Rails.application.routes.draw do

  namespace :public do
    get 'relationships/followings'
    get 'relationships/followers'
  end

  devise_for :users, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  scope module: :public do
    root :to => "homes#top"
    get "homes/about"
    get "posts/select_prefecture"
    get "posts/new/:id" => "posts#new", as: "post_new"
    resources :posts, only: [:index, :show, :create, :update] do
      resources :comments, only: [:create, :destroy]
      resources :bookmarks, only: [:create, :destroy]
    end
    resources :image_tags, only: [:destroy]
    resources :area_ratings, only: [:create]
    resources :records, only: [:create, :update, :destroy]
    resources :areas, only: [:show, :update]
    resources :prefectures, only: [:show]
    resources :regions, only: [:index]
    resources :information, only: [:index, :show]
    resources :users, only: [:show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
  end

  namespace :admin do
    root :to =>"homes#top"
    resources :posts, only: [:index, :show, :update, :destroy] do
      resources :comments, only: [:destroy]
    end
    resources :users, only: [:index, :show, :update]
    resources :areas, only: [:index, :create, :destroy, :update]
    resources :species, only: [:index, :create, :destroy]
    resources :fishing_methods, only: [:index, :create, :destroy]
    resources :information, only: [:index, :create, :destroy, :update, :new]
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord

  validates :prefecture_id, :name, :longitude, :latitude, presence: true

  belongs_to :prefecture
  has_many   :posts
  has_many   :area_ratings
  has_many_attached :image

  def get_image
    if image.attached?
      image[0]
    else
      "noimage.png"
    end
  end

end

app/models/area_rating.rb
class AreaRating < ApplicationRecord

  validates :user_id, :area_id, :comment, :score, presence: true

  belongs_to :area
  belongs_to :user
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord

  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: { scope: :post_id }

end

app/models/comment.rb
class Comment < ApplicationRecord

  validates :post_id, :user_id, :comment, presence: true

  belongs_to :user
  belongs_to :post

end

app/models/fishing_method.rb
class FishingMethod < ApplicationRecord

  validates :name, presence: true

  has_many :posts
end

app/models/image_tag.rb
class ImageTag < ApplicationRecord
	belongs_to :post
end

app/models/information.rb
class Information < ApplicationRecord

  validates :title, :body, presence: true

  has_many_attached :image

  def get_image
    if image.attached?
      image[0]
    else
      "noimage.png"
    end
  end

end

app/models/post.rb
class Post < ApplicationRecord

  validates :species_id, :user_id, :area_id, :fishing_method_id, :date, :time_zone_id, :catch_number, :comment, :title, presence: true

  belongs_to :user
  belongs_to :area
  belongs_to :species
  belongs_to :fishing_method
  belongs_to :time_zone
  has_many :image_tags, dependent: :destroy
  has_many   :post_tags, dependent: :destroy
  has_many   :prefectures, through: :post_tags
  has_many   :comments, dependent: :destroy
  has_many   :bookmarks, dependent: :destroy
  has_many_attached :image

  def bookmarked_by?(user)
    bookmarks.where(user_id: user).exists?
  end

  def get_post_image
    if image.attached?
      image[0]
    else
      "noimage.png"
    end
  end

  def self.search(search)
    if search
      where(['title LIKE ?', "%#{search}%"]) #検索とタイトルの部分一致を表示。
    else
      all #全て表示させる
    end
  end


end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :prefecture
end

app/models/prefecture.rb
class Prefecture < ApplicationRecord
  has_many :area
  has_many :users
  has_many :post_tags, dependent: :destroy
  has_many :posts, through: :post_tags
  belongs_to :region
  has_many_attached :image

  def get_post_image
    if image.attached?
      image[0]
    else
      "noimage.png"
    end
  end

  def get_prefecture_image(prefecture)
    "prefectures/#{prefecture.name}.png"
  end

end

app/models/record.rb
class Record < ApplicationRecord

  validates :user_id, :species_id, :size, :catch_number, presence: true

  belongs_to :user
  belongs_to :species
end

app/models/region.rb
class Region < ApplicationRecord

  has_many :prefecture

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/species.rb
class Species < ApplicationRecord

  validates :species, presence: true

  has_many :posts
  has_many :records
end

app/models/time_zone.rb
class TimeZone < ApplicationRecord
  has_many :posts
end

app/models/user.rb
class User < ApplicationRecord
  has_many   :posts, dependent: :destroy
  has_many   :bookmarks, dependent: :destroy
  has_many   :comments, dependent: :destroy
  has_many   :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many   :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many   :followings, through: :relationships, source: :followed, dependent: :destroy
  has_many   :followers, through: :reverse_of_relationships, source: :follower, dependent: :destroy
  has_many   :area_ratings, dependent: :destroy
  has_many   :records, dependent: :destroy
  belongs_to :prefecture
  has_one_attached :image
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def get_image
    if image.attached?
      image
    else
      "noimage.png"
    end
  end

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

end

app/controllers/admin/areas_controller.rb
class Admin::AreasController < ApplicationController

  before_action :authenticate_admin!

  def index
    @areas = Area.all.page(params[:page]).per(15) #全ての釣り場データを取得
    @new_area = Area.new #新規登録用のデータを取得
  end

  def create
    @area = Area.new(area_params) #送られてきたデータを取得
    @area.save #データを保存
    redirect_to request.referer #釣り場一覧画面に遷移
  end

  def destroy
    area = Area.find(params[:id]) #削除する釣り場のデータを取得
    area.destroy #データを削除
    redirect_to request.referer #釣り場一覧画面に遷移
  end

  def update
    area = Area.find(params[:id]) #編集する釣り場のデータを取得
    area.update(area_params) #データを保存
    redirect_to request.referer #釣り場一覧画面へ遷移
  end


  private

  def area_params #受信するデータの選択
    params.require(:area).permit(:name, :prefecture_id, :longitude, :latitude)
  end

end

app/helpers/admin/areas_helper.rb
module Admin::AreasHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/areas/index.html.erb
<!-- ヘッダー -->
<header class="bg-dark py-4">
  <div class="container px-4 px-lg-5">
    <div class="text-center text-white">
      <h2 class="fw-bolder">釣り場一覧</h2>
    </div>
  </div>
</header>
<!-- 釣り場の一覧を表示 -->
<section class="bg-light">
  <div class="container-fluid px-0">
    <div class="row">
      <%= render "admin/homes/sidebar" %>
      <div class="col-10 px-4">
        <table class="table mt-3 mb-0">
          <tr>
            <th>登録日</th>
            <th>都道府県</th>
            <th>名前</th>
            <th>投稿数</th>
            <th>経度</th>
            <th>緯度</th>
            <th></th>
          </tr>
          <% @areas.each do |area| %>
            <tr>
              <td><%= area.created_at.strftime('%Y/%m/%d') %></td>
              <td><%= area.prefecture.name %></td>
              <td><%= area.name %></td>
              <td><%= area.posts.count %>件</td>
              <td><%= area.longitude %></td>
              <td><%= area.latitude %></td>
              <td><%= link_to "削除", admin_area_path(area), method: :delete, class: "btn btn-outline-danger", "data-confirm" => "本当に削除しますか？" %></td>
            </tr>
          <% end %>
          <%= form_with model: @new_area, url: admin_areas_path, class: "d-flex align-items-center", method: :post do |f| %>
          <tr>
            <td>新規登録</td>
            <td><%= f.collection_select :prefecture_id, Prefecture.all, :id, :name, { prompt: '都道府県' }, class: "form-control mb-3" %></td>
            <td><%= f.text_field :name, class: "form-control", placeholder: "釣り場名" %></td>
            <td></td>
            <td><%= f.text_field :longitude, class: "form-control", placeholder: "経度" %></td>
            <td><%= f.text_field :latitude, class: "form-control", placeholder: "緯度" %></td>
            <td><%= f.submit "追加", class: "btn btn-outline-success" %></td>
          </tr>
          <% end %>
        </table>
      </div>
    </div>
    <div class="row">
      <!-- ページネーションのページ選択 -->
      <div class="text-center mx-auto mb-2"><%= paginate @areas %></div>
    </div>
  </div>
</section>