config/routes.rb
Rails.application.routes.draw do

  namespace :public do
    get 'relationships/followings'
    get 'relationships/followers'
  end

  devise_for :users, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  scope module: :public do
    root :to => "homes#top"
    get "homes/about"
    get "posts/select_prefecture"
    get "posts/new/:id" => "posts#new", as: "post_new"
    resources :posts, only: [:index, :show, :create, :update] do
      resources :comments, only: [:create, :destroy]
      resources :bookmarks, only: [:create, :destroy]
    end
    resources :image_tags, only: [:destroy]
    resources :area_ratings, only: [:create]
    resources :records, only: [:create, :update, :destroy]
    resources :areas, only: [:show, :update]
    resources :prefectures, only: [:show]
    resources :regions, only: [:index]
    resources :information, only: [:index, :show]
    resources :users, only: [:show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
  end

  namespace :admin do
    root :to =>"homes#top"
    resources :posts, only: [:index, :show, :update, :destroy] do
      resources :comments, only: [:destroy]
    end
    resources :users, only: [:index, :show, :update]
    resources :areas, only: [:index, :create, :destroy, :update]
    resources :species, only: [:index, :create, :destroy]
    resources :fishing_methods, only: [:index, :create, :destroy]
    resources :information, only: [:index, :create, :destroy, :update, :new]
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord

  validates :prefecture_id, :name, :longitude, :latitude, presence: true

  belongs_to :prefecture
  has_many   :posts
  has_many   :area_ratings
  has_many_attached :image

  def get_image
    if image.attached?
      image[0]
    else
      "noimage.png"
    end
  end

end

app/models/area_rating.rb
class AreaRating < ApplicationRecord

  validates :user_id, :area_id, :comment, :score, presence: true

  belongs_to :area
  belongs_to :user
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord

  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: { scope: :post_id }

end

app/models/comment.rb
class Comment < ApplicationRecord

  validates :post_id, :user_id, :comment, presence: true

  belongs_to :user
  belongs_to :post

end

app/models/fishing_method.rb
class FishingMethod < ApplicationRecord

  validates :name, presence: true

  has_many :posts
end

app/models/image_tag.rb
class ImageTag < ApplicationRecord
	belongs_to :post
end

app/models/information.rb
class Information < ApplicationRecord

  validates :title, :body, presence: true

  has_many_attached :image

  def get_image
    if image.attached?
      image[0]
    else
      "noimage.png"
    end
  end

end

app/models/post.rb
class Post < ApplicationRecord

  validates :species_id, :user_id, :area_id, :fishing_method_id, :date, :time_zone_id, :catch_number, :comment, :title, presence: true

  belongs_to :user
  belongs_to :area
  belongs_to :species
  belongs_to :fishing_method
  belongs_to :time_zone
  has_many :image_tags, dependent: :destroy
  has_many   :post_tags, dependent: :destroy
  has_many   :prefectures, through: :post_tags
  has_many   :comments, dependent: :destroy
  has_many   :bookmarks, dependent: :destroy
  has_many_attached :image

  def bookmarked_by?(user)
    bookmarks.where(user_id: user).exists?
  end

  def get_post_image
    if image.attached?
      image[0]
    else
      "noimage.png"
    end
  end

  def self.search(search)
    if search
      where(['title LIKE ?', "%#{search}%"]) #検索とタイトルの部分一致を表示。
    else
      all #全て表示させる
    end
  end


end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :prefecture
end

app/models/prefecture.rb
class Prefecture < ApplicationRecord
  has_many :area
  has_many :users
  has_many :post_tags, dependent: :destroy
  has_many :posts, through: :post_tags
  belongs_to :region
  has_many_attached :image

  def get_post_image
    if image.attached?
      image[0]
    else
      "noimage.png"
    end
  end

  def get_prefecture_image(prefecture)
    "prefectures/#{prefecture.name}.png"
  end

end

app/models/record.rb
class Record < ApplicationRecord

  validates :user_id, :species_id, :size, :catch_number, presence: true

  belongs_to :user
  belongs_to :species
end

app/models/region.rb
class Region < ApplicationRecord

  has_many :prefecture

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/species.rb
class Species < ApplicationRecord

  validates :species, presence: true

  has_many :posts
  has_many :records
end

app/models/time_zone.rb
class TimeZone < ApplicationRecord
  has_many :posts
end

app/models/user.rb
class User < ApplicationRecord
  has_many   :posts, dependent: :destroy
  has_many   :bookmarks, dependent: :destroy
  has_many   :comments, dependent: :destroy
  has_many   :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many   :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many   :followings, through: :relationships, source: :followed, dependent: :destroy
  has_many   :followers, through: :reverse_of_relationships, source: :follower, dependent: :destroy
  has_many   :area_ratings, dependent: :destroy
  has_many   :records, dependent: :destroy
  belongs_to :prefecture
  has_one_attached :image
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def get_image
    if image.attached?
      image
    else
      "noimage.png"
    end
  end

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  before_action :authenticate_admin!

  def index
    @users = User.all.page(params[:page]).per(15) #全ての投稿データを取得
  end

  def show
    @user = User.find(params[:id]) #特定のユーザーのデータを取得
    @posts = @user.posts #特定のユーザーの投稿を取得
  end

  def edit
    @user = User.find(params[:id]) #特定のユーザーのデータを取得
  end

  def update
    user = User.find(params[:id]) #特定のユーザーのデータを取得
    user.is_deleted = params[:is_deleted]
    user.save #送られてきたデータを保存
    redirect_to request.referer #元のページに戻る
  end

  private

  def user_params
    params.require(:is_deleted)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/users/index.html.erb
<!-- ヘッダー -->
<header class="bg-dark py-4">
  <div class="container px-4 px-lg-5">
    <div class="text-center text-white">
      <h2 class="fw-bolder">ユーザー一覧</h2>
    </div>
  </div>
</header>
<!-- ユーザーの一覧を表示 -->
<section class="bg-light">
  <div class="container-fluid px-0">
    <div class="row">
      <%= render "admin/homes/sidebar" %>
      <div class="col-10 px-4">
        <table class="table my-3">
          <tr>
            <th>登録日</th>
            <th>ユーザー名</th>
            <th>投稿件数</th>
            <th>フォロー数</th>
            <th>フォロワー数</th>
            <th>退会ステータス</th>
            <th></th>
          </tr>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.created_at.strftime('%Y/%m/%d') %></td>
              <td><%= user.name %></td>
              <td><%= user.posts.count %>件</td>
              <td><%= user.followings.count %>人</td>
              <td><%= user.followers.count %>人</td>
              <td><%= user.is_deleted %></td>
              <td>
                <% if user.is_deleted %>
                  <%= link_to "切り替え", admin_user_path(user, is_deleted: false), class: "btn btn-danger", method: :put %>
                <% else %>
                  <%= link_to "切り替え", admin_user_path(user, is_deleted: true), class: "btn btn-success", method: :put %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </table>
      </div>
    </div>
    <div class="row">
      <!-- ページネーションのページ選択 -->
      <div class="text-center mx-auto mb-2"><%= paginate @users %></div>
    </div>
  </div>
</section>

app/views/admin/users/show.html.erb
<h2 class="text-center my-4">投稿詳細</h2>
<div class>
  <div class="col-8 offset-2">
    <%= image_tag @user.get_image, height: "200" %>
  </div>
  <table class="col-8 table table-borderless">
    <tr>
      <th class="text-center" sytle="width: 200px">ユーザー名</th>
      <td><%= @user.name %></td>
    </tr>
    <tr>
      <th class="text-center">拠点</th>
      <td><%= @user.prefecture.name %></td>
    </tr>
    <tr>
      <th class="text-center" style="width: 200px">投稿数</th>
      <td><%= @user.posts.count %>件</td>
    </tr>
    <tr>
      <th class="text-center">釣果数</th>
      <td><%= @user.posts.sum(:catch_number) %>匹</td>
    </tr>
  </table>
</div>
<div class="row">
  <div class="col-6 text-center border">
    <div class="my-2">投稿一覧</div>
    <% if @user.posts.present? %>
      <% @user.posts.each do |post| %>
        <%= form_with model: post do |f| %>
          <div class="d-flex my-3 justify-content-center align-items-center">
            <div><%= link_to "#{post.title}", post_path(post.id), class: "mx-3" %></div>
            <div><%= f.select :status, [["公開","true"], ["非公開","false"]] %></div>
            <div><%= f.submit "変更", class: "btn btn-success btn-sm my-auto" %></div>
          </div>
        <% end %>
      <% end %>
    <% else %>
      投稿はありません
    <% end %>
  </div>
</div>