config/routes.rb
Rails.application.routes.draw do

  namespace :public do
    get 'relationships/followings'
    get 'relationships/followers'
  end

  devise_for :users, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  scope module: :public do
    root :to => "homes#top"
    get "homes/about"
    get "posts/select_prefecture"
    get "posts/new/:id" => "posts#new", as: "post_new"
    resources :posts, only: [:index, :show, :create, :update] do
      resources :comments, only: [:create, :destroy]
      resources :bookmarks, only: [:create, :destroy]
    end
    resources :image_tags, only: [:destroy]
    resources :area_ratings, only: [:create]
    resources :records, only: [:create, :update, :destroy]
    resources :areas, only: [:show, :update]
    resources :prefectures, only: [:show]
    resources :regions, only: [:index]
    resources :information, only: [:index, :show]
    resources :users, only: [:show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
  end

  namespace :admin do
    root :to =>"homes#top"
    resources :posts, only: [:index, :show, :update, :destroy] do
      resources :comments, only: [:destroy]
    end
    resources :users, only: [:index, :show, :update]
    resources :areas, only: [:index, :create, :destroy, :update]
    resources :species, only: [:index, :create, :destroy]
    resources :fishing_methods, only: [:index, :create, :destroy]
    resources :information, only: [:index, :create, :destroy, :update, :new]
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord

  validates :prefecture_id, :name, :longitude, :latitude, presence: true

  belongs_to :prefecture
  has_many   :posts
  has_many   :area_ratings
  has_many_attached :image

  def get_image
    if image.attached?
      image[0]
    else
      "noimage.png"
    end
  end

end

app/models/area_rating.rb
class AreaRating < ApplicationRecord

  validates :user_id, :area_id, :comment, :score, presence: true

  belongs_to :area
  belongs_to :user
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord

  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: { scope: :post_id }

end

app/models/comment.rb
class Comment < ApplicationRecord

  validates :post_id, :user_id, :comment, presence: true

  belongs_to :user
  belongs_to :post

end

app/models/fishing_method.rb
class FishingMethod < ApplicationRecord

  validates :name, presence: true

  has_many :posts
end

app/models/image_tag.rb
class ImageTag < ApplicationRecord
	belongs_to :post
end

app/models/information.rb
class Information < ApplicationRecord

  validates :title, :body, presence: true

  has_many_attached :image

  def get_image
    if image.attached?
      image[0]
    else
      "noimage.png"
    end
  end

end

app/models/post.rb
class Post < ApplicationRecord

  validates :species_id, :user_id, :area_id, :fishing_method_id, :date, :time_zone_id, :catch_number, :comment, :title, presence: true

  belongs_to :user
  belongs_to :area
  belongs_to :species
  belongs_to :fishing_method
  belongs_to :time_zone
  has_many :image_tags, dependent: :destroy
  has_many   :post_tags, dependent: :destroy
  has_many   :prefectures, through: :post_tags
  has_many   :comments, dependent: :destroy
  has_many   :bookmarks, dependent: :destroy
  has_many_attached :image

  def bookmarked_by?(user)
    bookmarks.where(user_id: user).exists?
  end

  def get_post_image
    if image.attached?
      image[0]
    else
      "noimage.png"
    end
  end

  def self.search(search)
    if search
      where(['title LIKE ?', "%#{search}%"]) #検索とタイトルの部分一致を表示。
    else
      all #全て表示させる
    end
  end


end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :prefecture
end

app/models/prefecture.rb
class Prefecture < ApplicationRecord
  has_many :area
  has_many :users
  has_many :post_tags, dependent: :destroy
  has_many :posts, through: :post_tags
  belongs_to :region
  has_many_attached :image

  def get_post_image
    if image.attached?
      image[0]
    else
      "noimage.png"
    end
  end

  def get_prefecture_image(prefecture)
    "prefectures/#{prefecture.name}.png"
  end

end

app/models/record.rb
class Record < ApplicationRecord

  validates :user_id, :species_id, :size, :catch_number, presence: true

  belongs_to :user
  belongs_to :species
end

app/models/region.rb
class Region < ApplicationRecord

  has_many :prefecture

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/species.rb
class Species < ApplicationRecord

  validates :species, presence: true

  has_many :posts
  has_many :records
end

app/models/time_zone.rb
class TimeZone < ApplicationRecord
  has_many :posts
end

app/models/user.rb
class User < ApplicationRecord
  has_many   :posts, dependent: :destroy
  has_many   :bookmarks, dependent: :destroy
  has_many   :comments, dependent: :destroy
  has_many   :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many   :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many   :followings, through: :relationships, source: :followed, dependent: :destroy
  has_many   :followers, through: :reverse_of_relationships, source: :follower, dependent: :destroy
  has_many   :area_ratings, dependent: :destroy
  has_many   :records, dependent: :destroy
  belongs_to :prefecture
  has_one_attached :image
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def get_image
    if image.attached?
      image
    else
      "noimage.png"
    end
  end

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container justify-content-center px-0">
    <ul class="navbar-nav">
      <li class="nav-item"><%= link_to "利用規約", root_path, class: "nav-link" %></li>
      <li class="nav-item"><%= link_to "プライバシーポリシー", root_path, class: "nav-link" %></li>
      <li class="nav-item"><%= link_to "お問い合わせ", root_path, class: "nav-link" %></li>
    </ul>
  </div>
</nav>
<div class="row m-0 text-center bg-dark text-white">
  <div class="container mb-3 text-center text-white">Copyright © 2022 Tsurireki All Rights Reserved.</div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark border-bottom">
  <div class="container px-5">
    <!-- アプリケーションタイトル -->
    <%= link_to "つりれき", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse text-center" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto mb-2 mb-lg-0">
        <!-- 共通のナビゲーションバー -->
        <li class="nav-item"><%= link_to "投稿一覧", posts_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "釣り場一覧", regions_path, class: "nav-link" %></li>
        <% if user_signed_in? %>
          <!-- ユーザーログイン時のナビゲーションバー -->
          <li class="nav-item"><%= link_to "新規投稿", posts_select_prefecture_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "ログアウト", destroy_user_session_path, class: "nav-link", method: :delete %></li>
          <li class="nav-item"><%= link_to "マイページ", user_path(current_user), class: "nav-link" %></li>
        <% elsif admin_signed_in? %>
          <!-- 管理者ログイン時のナビゲーションバー -->
          <li class="nav-item"><%= link_to "ログアウト", destroy_admin_session_path, class: "nav-link", method: :delete %></li>
          <li class="nav-item"><%= link_to "管理画面", admin_root_path, class: "nav-link" %></li>
        <% else %>
          <!-- 非ログイン時のナビゲーションバー -->
          <li class="nav-item"><%= link_to "ログイン", new_user_session_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "新規登録", new_user_registration_path, class: "nav-link" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_notifications.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "#{key} col-12 text-center p-0 m-0") %>
<% end %>
<% flash.clear %>

app/views/layouts/_sidebar_left.html.erb
<div class="col-2 border">
  <% @sidebar_posts.each do |post| %>
    <div class="text-truncate"><%= post.title %></div>
    <div class="text-truncate"><%= post.species.name %></div>
    <div class="border-bottom text-truncate"><%= post.created_at.strftime('%Y/%m/%d') %></div>
  <% end %>
</div>

app/views/layouts/_sidebar_right.html.erb
<div class="col-2 border p-0">
  <% if user_signed_in? %>
    <div class="card text-center m-0">
      <%= image_tag current_user.get_image %></br>
      <%= current_user.name %>さん
      <div class="card-body mx-auto">
        <p class="card-text text-center">
          <%= link_to "マイページ", user_path(current_user.id) %>
        </p>
        <p class="card-text text-center">
          投稿数 <%= current_user.posts.count %>件
        </p>
        <p class="card-text text-center">
          釣果数 <%= current_user.posts.sum(:catch_number) %>匹
        </p>
        <p class="card-text text-center">
          フォロー <%= current_user.followings.count %>人
        </p>
        <p class="card-text text-center">
          フォロワー <%= current_user.followers.count %>人
        </p>
        <p class="card-text text-center">
          ブックマーク <%= current_user.bookmarks.count %>件
        </p>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tsurireki</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navigation" %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>

</html>